# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - echo 'Clone images from the docker release step'
builds:
  - skip: true
  
release:
  prerelease: allow # remove this when we start publishing non-prerelease or set to auto
  footer: |
    ### Thanks to all contributors!

# modelines, feel free to remove those if you don't want/use them:
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj