name: 'release'

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: 'write'
  packages: 'write'

jobs:
  release:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'docker/setup-qemu-action@8b122486cedac8393e77aa9734c3528886e4a1a8' # ratchet:docker/setup-qemu-action@v2

      - uses: 'actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b' # ratchet:actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: 'actions/setup-go@84cbf8094393cdc5fe1fe1671ff2647332956b1a' # ratchet:actions/setup-go@v3
        with:
          go-version: '1.19'

      - uses: 'docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b' # ratchet:docker/login-action@v2
        with:
          registry: 'ghcr.io'
          username: '${{ github.actor }}'
          password: '${{ secrets.GITHUB_TOKEN }}'

      - uses: 'goreleaser/goreleaser-action@68acf3b1adf004ac9c2f0a4259e85c5f66e99bef' # ratchet:goreleaser/goreleaser-action@v3
        with:
          version: 'latest'
          args: 'release --rm-dist'
        env:
          CONTAINER_REGISTRY: ghcr.io/yolocs
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'